<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>
		<?php if (not_empty($me['new_notifs'])): ?>
			(<?php echo fetch_or_get($me['new_notifs']); ?>)
		<?php endif; ?>
		
		<?php echo fetch_or_get($cl["page_title"], cl_text_secure($cl["config"]["title"])); ?>
	</title>

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="title" content="<?php echo fetch_or_get($cl["page_title"], ''); ?>"/>
    <meta name="description" content="<?php echo fetch_or_get($cl["page_desc"], ''); ?>"/>
    <meta name="keywords" content="<?php echo fetch_or_get($cl['page_kw'], '');?>"/>
    <meta name="image" content="<?php echo fetch_or_get($cl['page_img'], cl_link(cl_strf('themes/%s/statics/img/og-banner.jpg', $cl['config']['theme'])));?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<?php if ($cl["pn"] == 'thread'): ?>
		<meta property="og:type" content="article" />
		<meta property="og:image" content="<?php echo fetch_or_get($cl["page_image"], ''); ?>"/>
		<meta property="og:image" content="<?php echo fetch_or_get($cl["page_image"], ''); ?>" />
		<meta property="og:image:secure_url" content="<?php echo fetch_or_get($cl["page_image"], ''); ?>" />
		<meta property="og:description" content="<?php echo fetch_or_get($cl["page_desc"], ''); ?>" />
		<meta property="og:title" content="<?php echo fetch_or_get($cl["page_title"], ''); ?>" />
		<meta property="og:url" content="<?php echo fetch_or_get($cl["page_url"], $cl["config"]["url"]); ?>" />
		<meta name="twitter:card" content="summary">
		<meta name="twitter:title" content="<?php echo fetch_or_get($cl["page_title"], ''); ?>" />
		<meta name="twitter:description" content="<?php echo fetch_or_get($cl["page_desc"], ''); ?>" />
		<meta name="twitter:image" content="<?php echo fetch_or_get($cl["page_image"], ''); ?>" />
	<?php endif; ?>

	<?php if (in_array($cl["pn"], array("profile", "connections"))): ?>
		<?php if ($cl['prof_user']['index_privacy'] == 'N'): ?>
		    <meta name="robots" content="noindex">
		    <meta name="googlebot" content="noindex">
	    <?php endif; ?>
    <?php endif; ?>

	<link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/animate.min.css?v=<?php echo($cl["update_date"]); ?>">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/css-libs.css">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/jquery.toast.min.css">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/master.styles.css?v=<?php echo($cl["update_date"]); ?>">

	<?php if ($cl["curr_lang"]["lang_data"]["is_rtl"] == "Y"): ?>
		<link rel="stylesheet" href="{%config theme_url%}/statics/css/master.styles.rtl.css?v=<?php echo($cl["update_date"]); ?>">
	<?php endif; ?>

	<link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/jquery.fancybox.css?v=<?php echo($cl["update_date"]); ?>">
	<link rel="stylesheet" href="{%config theme_url%}/statics/js/libs/plyr/plyr-code/plyr.css?v=<?php echo($cl["update_date"]); ?>">
	<link rel="icon" href="{%config site_fav%}" type="image/png">
	<link rel="icon" href="{%config site_fav%}" type="image/x-icon">
	<link rel="manifest" href="/manifest.json">

	<script src="{%config theme_url%}/statics/js/libs/jquery-3.5.1.min.js?v=<?php echo($cl["update_date"]); ?>"></script>
	<?php if ($cl["server_mode"] == 'dev'): ?>
		<script src="{%config theme_url%}/statics/js/libs/vuejs/vue-v2.6.11.dev.min.js?v=<?php echo($cl["update_date"]); ?>"></script>
	<?php else: ?>
		<script src="{%config theme_url%}/statics/js/libs/vuejs/vue-v2.6.11.min.js?v=<?php echo($cl["update_date"]); ?>"></script>
	<?php endif; ?>

	<?php if (not_empty($cl["is_logged"]) && $cl["config"]["push_notifs"] == 'on'): ?>
		<script src="{%config theme_url%}/statics/js/libs/OneSignal/OneSignalSDK.js?v=<?php echo($cl["update_date"]); ?>"></script>

		<script>
		  window.OneSignal = window.OneSignal || [];
		  var cl_web_push_user_id = "<?php echo $cl["me"]["web_device_id"]; ?>";
		  var onesig_push_user_id = "";

		  OneSignal.push(function() {
		    OneSignal.init({
		      appId: "<?php echo $cl["config"]["onesignal_app_id"]; ?>",
		      autoRegister: true,
		      notifyButton: {
		        enable: true
		      },
		      persistNotification: false,
		      allowLocalhostAsSecureOrigin: true,
		      promptOptions: {
			      slidedown: {
			        prompts: [
			          {
			            type: "push",
			            autoPrompt: true,
			            text: {
			              actionMessage: "<?php echo cl_translate("{@site_name@} would like to send you notifications", array("site_name" => $cl["config"]["name"])); ?>",
			              acceptButton: "<?php cl_translate("Allow"); ?>",
			              cancelButton: "<?php cl_translate("Cancel"); ?>"
			            },
			            delay: {
			              pageViews: 1,
			              timeDelay: 20
			            }
			          }
			        ]
			      }
			    }
		    });

		    OneSignal.getUserId(function(onesig_user_id) {
	            onesig_push_user_id = onesig_user_id;

	            if (onesig_user_id != cl_web_push_user_id) {
	            	$.ajax({
	            		url: "<?php echo cl_link("native_api/main/update_web_device_id"); ?>",
	            		type: "POST",
	            		dataType: "json",
	            		data: {id: onesig_push_user_id},
	            	}).done(function(data) {
	            		if (data.status == 200) {
	            			console.log("Web device ID has been successfully updated. [OneSignal push notifications alert]");
	            		}
	            		else{
	            			console.log("Failed to update web device ID. [OneSignal push notifications alert]");
	            		}
	            	});
	            }
	        });

	        OneSignal.on('subscriptionChange', function (isSubscribed) {
				if (isSubscribed == true) {
					$.ajax({
	            		url: "<?php echo cl_link("native_api/main/update_web_device_id"); ?>",
	            		type: "POST",
	            		dataType: "json",
	            		data: {id: onesig_push_user_id},
	            	}).done(function(data) {
	            		if (data.status == 200) {
	            			console.log("Web device ID has been successfully updated. [OneSignal push notifications alert]");
	            		}
	            		else{
	            			console.log("Failed to update web device ID. [OneSignal push notifications alert]");
	            		}
	            	});
				} 

				else {
				    $.ajax({
	            		url: "<?php echo cl_link("native_api/main/delete_web_device_id"); ?>",
	            		type: "POST",
	            		dataType: "json"
	            	}).done(function(data) {
	            		if (data.status == 200) {
	            			console.log("Web device ID has been successfully deleted. [OneSignal push notifications alert]");
	            		}
	            		else{
	            			console.log("Failed to delete web device ID. [OneSignal push notifications alert]");
	            		}
	            	});
				}
			});
		  });
		</script>
	<?php endif; ?>
	
	<script src="{%config theme_url%}/statics/js/libs/vuejs/vue-plugins/validators.min.js?v=<?php echo($cl["update_date"]); ?>"></script>

	<?php if ($cl['config']['stripe_method_status'] == 'on'): ?>
		<script src="https://js.stripe.com/v3/"></script>
	<?php endif; ?>

	<?php if ($cl['config']['rzp_method_status'] == 'on'): ?>
		<script src="{%config theme_url%}/statics/js/libs/Razorpay/checkout.js?v=<?php echo($cl["update_date"]); ?>"></script>
	<?php endif; ?>
	
	<script src="{%config theme_url%}/statics/js/libs/vuejs/vue-plugins/vuelidate.min.js?v=<?php echo($cl["update_date"]); ?>"></script>
	<script src="{%config theme_url%}/statics/js/libs/jquery-plugins/jquery.form-v4.2.2.min.js?v=<?php echo($cl["update_date"]); ?>"></script>
	<script src="{%config theme_url%}/statics/js/libs/popper.1.12.9.min.js?v=<?php echo($cl["update_date"]); ?>"></script>
	<script src="{%config theme_url%}/statics/js/libs/bootstrap.v4.0.0.min.js?v=<?php echo($cl["update_date"]); ?>"></script>
	<script src="{%config theme_url%}/statics/js/libs/sticky-sidebar/source/jquery.sticky-sidebar.js?v=<?php echo($cl["update_date"]); ?>"></script>
	<script src="{%config theme_url%}/statics/js/master.script.js?v=<?php echo($cl["update_date"]); ?>"></script>
	<script src="{%config theme_url%}/statics/js/custom.js?v=<?php echo($cl["update_date"]); ?>"></script>
	<script src="{%config theme_url%}/statics/js/libs/clipboard.min.js?v=<?php echo($cl["update_date"]); ?>"></script>
	<script src="{%config theme_url%}/statics/js/libs/jquery-plugins/jquery.fancybox.min.js?v=<?php echo($cl["update_date"]); ?>"></script>
	<script src="{%config theme_url%}/statics/js/libs/lozad.min.js"></script>
	<script src="{%config theme_url%}/statics/js/libs/waitme/waitMe.min.js"></script>
	<script src="{%config theme_url%}/statics/js/libs/txt.autoresize.min.js"></script>
	<script src="{%config theme_url%}/statics/js/libs/audio-recorder.js"></script>
	<script src="{%config theme_url%}/statics/js/libs/plyr/plyr-code/plyr.min.js"></script>
	<script src="{%config theme_url%}/statics/js/libs/readmore.js"></script>
	<script src="{%config theme_url%}/statics/js/libs/jquery-plugins/jquery-toast.min.js"></script>
	
	<script>
		if ('serviceWorker' in navigator) {
		    window.addEventListener('load', function() {
		      navigator.serviceWorker.register('/themes/default/statics/js/service-worker.js').then(function(registration) {
		        console.log('Service Worker registered with scope:', registration.scope);
		      }).catch(function(error) {
		        console.log('Service Worker registration failed:', error);
		      });
		    });
		}
	</script>

	<?php if ($cl["pn"] == "guest" && $cl["auth_type"] == "signup"): ?>
		<?php if ($cl["config"]["google_recaptcha"] == "on"): ?>
			<script src='https://www.google.com/recaptcha/api.js' async defer></script>
		<?php endif; ?>
	<?php endif; ?>

	<script>
		<?php echo(cl_get_custom_code("headerjs")); ?>
	</script>
	<style>
		<?php echo(cl_get_custom_code("headercss")); ?>
	</style>

	<?php echo cl_template('custom/header_tags'); ?>
</head>
<body <?php if ($cl["curr_lang"]["lang_data"]["is_rtl"] == "Y"){echo('dir="rtl"');} else{echo('dir="ltr"');} ?> class="cl-app-<?php echo fetch_or_get($cl["pn"], "none"); ?> <?php echo (($cl["is_logged"]) ? "" : "body-guest-mode" ); ?>" data-page-tab="<?php echo fetch_or_get($cl["page_tab"], "none"); ?>" data-skin="<?php echo($cl["display_set"]["color_scheme"]); ?>" data-bg="<?php echo($cl["display_set"]["background"]); ?>">
	<div class="main-preloader-holder" id="main-preloader-holder">
		<div class="main-preloader">
			<div class="loading">
				<img src="{%config site_logo%}" alt="Logo">
			</div>
		</div>
	</div>
	<div data-el="main-content-holder">
		<main class="main-content-container <?php echo (($cl["is_logged"]) ? "" : "guest-mode" ); ?>">
			<?php if ($cl["pn"] == "guest"): ?>
				<?php echo $cl["http_res"]; ?>
			<?php else: ?>
				<div class="main-content-container-inner">
					<?php if (not_empty($cl["sbl"])): ?>
						<?php if (not_empty($cl["is_logged"])): ?>
							<?php echo cl_template('main/left_sidebar'); ?>
						<?php else: ?>
							<?php echo cl_template('main/left_sidebar_guest'); ?>
						<?php endif; ?>
					<?php endif; ?>

					<div data-el="timeline-container-wrapper" class="timeline-container-wrapper">
						<div data-el="timeline-content" class="timeline-container-inner">
							<?php echo $cl["http_res"]; ?>
						</div>

						<div data-el="spa-preloader" class="spa-preloader d-none">
							<div class="spa-preloader-inner">
								<span class="spinner-icon">
									<?php echo cl_icon("spinner-icon"); ?>
								</span>
							</div>
						</div>
					</div>

					<?php if (not_empty($cl["sbr"])): ?>
						<?php echo cl_template('main/right_sidebar'); ?>
					<?php endif; ?>
				</div>
			<?php endif; ?>
		</main>

		<?php if (not_empty($cl["is_logged"]) && in_array($cl["pn"], array("conversation")) != true): ?>
			<?php echo cl_template('main/bottom_navbar'); ?>
		<?php endif; ?>

		<input id="csrf-token" type="hidden" class="hidden d-none" value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>">

		<?php if ($cl['is_logged']): ?>
			<div class="modal fade modal-pubbox" data-app="modal-pubbox" id="add_new_post" tabindex="-1" role="dialog" aria-hidden="true">
			    <div class="modal-dialog" role="document">
			        <div class="modal-content">
			            <div class="modal-header">
			                <div class="modal-header__inner">
			                    <h5 class="modal-title" data-an="modal-title">
			                    	<?php echo cl_translate('New post'); ?>
			                   	</h5>
			                    <span class="dismiss-modal" data-dismiss="modal">
			                        <?php echo cl_ficon('dismiss'); ?>
			                    </span>
			                </div>
			            </div>
			            <div class="modal-body">
			                <?php $cl['pb_id'] = 2; echo cl_template('timeline/pubbox'); ?>
			            </div>
			        </div>
			    </div>
			</div>
			<?php echo cl_template('timeline/scripts/pubbox_master_script'); ?>	
		<?php endif; ?>
		<div data-app="black-hole"></div>
		<?php if (not_empty($cl['config']['google_analytics'])): ?>
			<?php echo htmlspecialchars_decode($cl['config']['google_analytics']); ?>
		<?php endif; ?>

		<?php if ($cl["pn"] != 'guest'): ?>
			<?php echo cl_template("main/scripts/app_master_script"); ?>
		<?php endif; ?>

		<?php if ($cl['is_logged']): ?>
			<?php if (in_array($cl["pn"], array("bookmarks", "home", "profile", "search", "thread"))): ?>
				<?php echo cl_template("main/modals/report_post"); ?>
			<?php endif; ?>

			<?php echo cl_template("main/modals/display_settings"); ?>
		<?php endif; ?>
	</div>

	<?php if ($cl['config']['cookie_warning_popup'] == "on"): ?>
		<?php if (empty($_COOKIE['__c_u_a__'])): ?>
			<?php if ($cl["pn"] != "stat_pages"): ?>
				<?php echo cl_template("main/modals/cookies_alert"); ?>
			<?php endif; ?>
		<?php endif; ?>
	<?php endif; ?>

	<script>
		<?php echo(cl_get_custom_code("footerjs")); ?>
	</script>

	<?php echo cl_template('custom/footer_tags'); ?>
</body>
</html>

