<div class="left-sb-container sidebar" data-app="left-sidebar">
	<div class="sidebar__inner">
		<div class="sidebar__nav">
			<div class="sidebar__nav-group">
				
				<div data-navitem="home" class="sidebar__nav-item <?php if($cl['pn'] == 'home') {echo('active');} ?>">
					<span class="icon">
						<?php echo cl_ficon('home'); ?>
					</span>
					<span class="text">
						<a href="<?php echo cl_link('/'); ?>" data-spa="true">
							<?php echo cl_translate('Home'); ?>
						</a>
					</span>
				</div>

				<div data-navitem="notifications" class="sidebar__nav-item <?php if($cl['pn'] == 'notifications') {echo('active');} ?>">
					<span class="icon">
						<?php echo cl_ficon('notifications'); ?>
					</span>
					<span class="text">
						<a href="<?php echo cl_link("notifications"); ?>" data-spa="true">
							<?php echo cl_translate('Notifications'); ?>
							<span class="info-indicators" data-an="new-notifs"><?php echo fetch_or_get($me['new_notifs']); ?></span>
						</a>
					</span>
				</div>
				<div data-navitem="subscriptions" class="sidebar__nav-item <?php if($cl['pn'] == 'subscriptions') {echo('active');} ?>">
					<span class="icon">
						<?php echo cl_ficon('person_tag'); ?>
					</span>
					<span class="text">
						<a href="<?php echo cl_link("subscriptions"); ?>" data-spa="true">
							<?php echo cl_translate('Subscriptions'); ?>
						</a>
					</span>
				</div>

				<div data-navitem="chat" class="sidebar__nav-item <?php if($cl['pn'] == 'chat') {echo('active');} ?>">
					<span class="icon">
						<?php echo cl_ficon('chat'); ?>
					</span>
					<span class="text">
						<a href="<?php echo cl_link("chats"); ?>" data-spa="true">
							<?php echo cl_translate('Messages'); ?>
							<span class="info-indicators" data-an="new-messages"><?php echo fetch_or_get($me['new_messages']); ?></span>
						</a>
					</span>
				</div>
				<div data-navitem="search" class="sidebar__nav-item <?php if($cl['pn'] == 'search') {echo('active');} ?>">
					<span class="icon">
						<?php echo cl_ficon('compass_northwest'); ?>
					</span>
					<span class="text">
						<a href="<?php echo cl_link("search"); ?>" data-spa="true">
							<?php echo cl_translate('Explore'); ?>
						</a>
					</span>
				</div>
				<div data-navitem="profile" class="sidebar__nav-item <?php if($cl['pn'] == 'profile' && not_empty($cl["page_xdata"]) && not_empty($cl["page_xdata"]["is_me"])) {echo('active');} ?>">
					<span class="icon">
						<?php echo cl_ficon('person'); ?>
					</span>
					<span class="text">
						<a href="<?php echo($me["url"]); ?>" data-spa="true">
							<?php echo cl_translate('My profile'); ?>
						</a>
					</span>
				</div>
			</div>
			<div class="sidebar__nav-group sidebar__nav-group_collapse">
				
				<div class="sidebar__nav-item-devider"></div>
				<?php if (not_empty($cl['is_admin'])): ?>
					<div class="sidebar__nav-item">
						<span class="icon">
							<?php echo cl_ficon('shield'); ?>
						</span>
						<span class="text">
							<a href="<?php echo cl_link("admin_panel"); ?>" target="_blank">
								<?php echo cl_translate('Control panel'); ?>
							</a>
						</span>
					</div>
				<?php endif; ?>
				<?php if ($cl['config']['user_wallet_status'] == 'on'): ?>
					<div class="sidebar__nav-item-devider"></div>
					<div data-navitem="wallet" class="sidebar__nav-item <?php if($cl['pn'] == 'wallet') {echo('active');} ?>">
						<span class="icon">
							<?php echo cl_ficon('wallet'); ?>
						</span>
						<span class="text">
							<a href="<?php echo cl_link("wallet"); ?>" data-spa="true">
								<?php echo cl_translate('Wallet'); ?> <b class="wallet">(<?php echo cl_money($me['wallet']); ?>)</b>
							</a>
						</span>
					</div>
				<?php endif; ?>
				<?php if ($cl['config']['advertising_system'] == 'on'): ?>
					<div data-navitem="ads" class="sidebar__nav-item <?php if($cl['pn'] == 'ads') {echo('active');} ?>">
						<span class="icon">
							<?php echo cl_ficon('ads'); ?>
						</span>
						<span class="text">
							<a href="<?php echo cl_link("ads"); ?>" data-spa="true">
								<?php echo cl_translate('Advertising'); ?>
							</a>
						</span>
					</div>
				<?php endif; ?>
				<?php if ($cl['config']['affiliates_system'] == 'on'): ?>
					<div data-navitem="affiliates" class="sidebar__nav-item <?php if($cl['pn'] == 'affiliates') {echo('active');} ?>">
						<span class="icon">
							<?php echo cl_ficon('group_work'); ?>
						</span>
						<span class="text">
							<a href="<?php echo cl_link("affiliates"); ?>" data-spa="true">
								<?php echo cl_translate('Affiliates'); ?>
							</a>
						</span>
					</div>
				<?php endif; ?>
				
				<div class="sidebar__nav-item-devider"></div>
				<div data-navitem="settings" class="sidebar__nav-item <?php if($cl['pn'] == 'settings') {echo('active');} ?>">
					<span class="icon">
						<?php echo cl_ficon('settings'); ?>
					</span>
					<span class="text">
						<a href="<?php echo cl_link("settings"); ?>" data-spa="true">
							<?php echo cl_translate("Account settings"); ?>
						</a>
					</span>
				</div>
				<?php if ($cl['config']['prem_account_system_status'] == 'on'): ?>
					<?php if ($me["is_premium"] == 1): ?>
						<div data-navitem="premium_features" class="sidebar__nav-item <?php if($cl['pn'] == 'premium_features') {echo('active');} ?>">
							<span class="icon">
								<?php echo cl_ficon('premium'); ?>
							</span>
							<span class="text">
								<a href="<?php echo cl_link("premium_features"); ?>" data-spa="true">
									<?php echo cl_translate('Premium features'); ?>
								</a>
							</span>
						</div>
					<?php else: ?>
						<div data-navitem="premium_account" class="sidebar__nav-item <?php if($cl['pn'] == 'premium_account') {echo('active');} ?>">
							<span class="icon">
								<?php echo cl_ficon('premium'); ?>
							</span>
							<span class="text">
								<a href="<?php echo cl_link("premium_account"); ?>" data-spa="true">
									<?php echo cl_translate('Premium account'); ?>
								</a>
							</span>
						</div>
					<?php endif; ?>
				<?php endif; ?>
				<div data-navitem="bookmarks" class="sidebar__nav-item <?php if($cl['pn'] == 'bookmarks') {echo('active');} ?>">
					<span class="icon">
						<?php echo cl_ficon('bookmark'); ?>
					</span>
					<span class="text">
						<a href="<?php echo cl_link("bookmarks"); ?>" data-spa="true">
							<?php echo cl_translate('Bookmarks'); ?>
						</a>
					</span>
				</div>
				<div class="sidebar__nav-item">
					<span class="icon">
						<?php echo cl_ficon('content_settings'); ?>
					</span>
					<span class="text">
						<a href="javascript:void(0);" onclick="SMColibri.display_settings();">
							<?php echo cl_translate('Display settings'); ?>
						</a>
					</span>
				</div>
				<div class="sidebar__nav-item-devider"></div>
				<div class="sidebar__nav-item">
					<span class="icon">
						<?php echo cl_ficon('sign_out'); ?>
					</span>
					<span class="text">
						<a href="javascript:void(0);" onclick="SMColibri.logout();">
							<?php echo cl_translate('Logout'); ?>
						</a>
					</span>
				</div>
			</div>
			<div class="sidebar__nav-group sidebar__nav-group_toggle">
				<div class="sidebar__nav-item-devider"></div>
				<div class="sidebar__nav-item" onclick="SMColibri.toggleSBMenu(this);">
					<span class="icon">
						<?php echo cl_ficon('more_horiz'); ?>
					</span>
					<span class="text">
						<a href="javascript:void(0);" >
							<?php echo cl_translate('More'); ?>
						</a>
					</span>
				</div>
			</div>
		</div>
		<div class="sidebar__footer">
			<?php echo cl_template('main/footer'); ?>
		</div>
	</div>
</div>

