<div class="timeline-placeholder">
	<div class="icon">
		<div class="icon__bg">
			<?php echo cl_ficon('person_prohibited'); ?>
		</div>
	</div>

	<div class="pl-message">
		<h4>
			<?php echo cl_translate("This profile is disabled"); ?>
		</h4>
		<p>
			<?php echo cl_translate("This account has been disabled by the administration for violating the rules. If you have any questions about this, please contact our support team."); ?>
		</p>	
	</div>
</div>