<div class="hashtag-list-item"  data-list-item="<?php echo($cl['li']['id']); ?>">
	<a class="block-link" href="<?php echo($cl['li']['url']); ?>" data-spa="true">
		<div class="hashtag-data">
			<div class="hashtag-data__body">
				<span>
					<?php echo($cl['li']['hashtag']); ?>
				</span> 
				<span>
					<?php echo($cl['li']['total']); ?> <?php echo cl_translate('Posts'); ?>
				</span>
			</div>
			<div class="hashtag-data__right-icon">
				<?php echo cl_ficon('open'); ?>
			</div>
		</div>
	</a>
</div>