<div class="timeline-placeholder">
	<div class="icon">
		<div class="icon__bg">
			<?php echo cl_ficon('note'); ?>
		</div>
	</div>
	<div class="pl-message">
		<h4>
			<?php echo cl_translate("No posts yet!"); ?>
		</h4>
		<p>
			<?php echo cl_translate("It looks like there are no posts on your feed yet. All your posts and publications of people you follow will be displayed here."); ?>
		</p>
	</div>
</div>