<div class="cp-app-container">
    <div class="current-page-name">
        <div class="lp">
            <h1>
            	Your access is limited
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="body">
                	<div class="content-placeholder">
                		<h4>
	                		Access is denied
	                	</h4>
	                	<p>
	                		You have not been granted access rights to this admin section. If you have questions, <br> please contact the main admin so that he can activate the desired section for you
	                	</p>
                	</div>
                </div>
            </div>
        </div>
    </div>
</div>