<div class="cp-app-container" data-app="push-notifications">
    <div class="current-page-name">
        <div class="lp">
            <h1>
                Push notifications
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Manage push notifications API settings
                    </h2>
                </div>
                <div class="body">
                    <form class="form" data-an="form">
                    	<div class="row">
                            <div class="col-lg-6">
                                <div class="form-group" data-an="onesignal_app_id-input">
                                    <label>
                                        OneSignal App ID
                                    </label>
                                    <div class="form-line">
                                        <input value="{%config onesignal_app_id%}" name="onesignal_app_id" type="text" class="form-control" placeholder="Enter OneSignal App ID">
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group" data-an="onesignal_app_key-input">
                                    <label>
                                        OneSignal REST App Key
                                    </label>
                                    <div class="form-line">
                                        <input value="{%config onesignal_app_key%}" name="onesignal_app_key" type="text" class="form-control" placeholder="Enter OneSignal App Key">
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group" data-an="push_notifs-input">
                                    <label>
                                        Status
                                    </label>
                                    <div class="form-line form-select">
                                        <select name="push_notifs" class="form-control">
                                            <option value="on" <?php if($cl['config']['push_notifs'] == 'on') { echo('selected'); } ?>>On</option>
                                            <option value="off" <?php if($cl['config']['push_notifs'] == 'off') { echo('selected'); } ?>>Off</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        
                        <div class="form-group no-mb">
                       		<button data-an="submit-ctrl" type="submit" class="btn btn-primary">
                                Save changes
                            </button>
                        </div>
                        <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>" name="hash">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo cl_template('cpanel/assets/push_notifications/scripts/app_master_script'); ?>