<tr data-list-item="<?php echo($cl['li']['id']); ?>">
    <td>
        <?php echo($cl['li']['id']); ?>
    </td>
    <td>
        <div class="user-info-holder">
            <div class="avatar-holder">
                <img src="<?php echo($cl['li']['avatar']); ?>" alt="Avatar">
            </div>
            <div class="uname-holder">
                <b>
                    <?php echo($cl['li']['full_name']); ?>
                </b>
                <a href="<?php echo($cl['li']['url']); ?>">
                    <?php echo($cl['li']['username']); ?>
                </a>
            </div>
        </div>
    </td>
    <td>
        <span>
            <?php echo($cl['li']['email']); ?>
        </span>
    </td>
    <td>
        <span class="badge bg-blue">
            <?php echo($cl['li']['method']); ?>
        </span>
    </td>
    <td>
        <?php echo cl_money($cl['li']['amount']); ?>
    </td>
    <td>
        <time>
            <?php echo ($cl['li']['time']); ?>
        </time>
    </td>
    <td>
        <div class="dropdown">
            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <?php echo cl_ficon("chevron_down"); ?>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <a onclick="CSMWithdrawalRequests.show(<?php echo($cl['li']['id']); ?>);" href="javascript:void(0);" class="dropdown-item">
                    Show details
                </a>
                <a onclick="CSMWithdrawalRequests.paid(<?php echo($cl['li']['id']); ?>);" href="javascript:void(0);" class="dropdown-item">
                    Mark as paid
                </a>
                <a onclick="CSMWithdrawalRequests.delete(<?php echo($cl['li']['id']); ?>);" href="javascript:void(0);" class="dropdown-item">
                    Delete
                </a>
            </ul>
        </div>
    </td>
</tr>