<div class="main-cont-inner" id="license-agreements-page">
	<div class="cont-header">
		<div class="row">
			<div class="col-12">
				<h2>
					<span class="icon">
						<svg  viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-labelledby="supportIconTitle"  stroke-width="1.8" stroke-linecap="square" stroke-linejoin="miter" fill="none" >  <path stroke-linecap="round" d="M11 8L9.42229 7.21115C9.14458 7.07229 8.83835 7 8.52786 7H7.82843C7.29799 7 6.78929 7.21071 6.41421 7.58579L5.58579 8.41421C5.21071 8.78929 5 9.29799 5 9.82843L5 14.9296C5 15.5983 5.3342 16.2228 5.8906 16.5937L9.75746 19.1716C10.4944 19.663 11.4668 19.611 12.1472 19.044L17 15"/> <path d="M14.4549 12.9142C13.8515 12.1062 12.741 11.8739 11.8643 12.3721L10.009 13.4266C9.41298 13.7653 8.66412 13.6641 8.17937 13.1794V13.1794C7.54605 12.546 7.59324 11.5056 8.2813 10.9323L12.4437 7.46356C12.8032 7.16403 13.2562 7 13.7241 7H14.5279C14.8384 7 15.1446 7.07229 15.4223 7.21115L17.8944 8.44721C18.572 8.786 19 9.47852 19 10.2361L19 12.9796C19 14.9037 16.5489 15.718 15.3976 14.1764L14.4549 12.9142Z"/> <path d="M1 17V8"/> <path d="M1 17V8"/> <path d="M23 17V8"/> </svg>
					</span>
					<span class="text">
						Terms of use (License Agreement)
					</span>
				</h2>
			</div>
		</div>
	</div>
	<div class="cont-body">
		<div class="terms-of-use">
			<div class="agreement-def-title">
				<p>
					In order to proceed with the installation of your site, you must first read and confirm that you agree to the terms of use of our product.

					<a href="https://codecanyon.net/licenses" target="_blank">
						Learn more about Codecanyon licenses <svg role="img" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 24 24" aria-labelledby="arrowRightTopIconTitle"  stroke-width="1.8" stroke-linecap="square" stroke-linejoin="miter" fill="none" >  <path d="M19 13V5h-8"/> <path stroke-linecap="round" d="M19 5l-1 1"/> <path d="M18 6L5 19"/> </svg>
					</a>
				</p>
			</div>
			<div class="row align-items-sretch item-license-perms-wrapper">
				<div class="col-xl-6">
					<div class="item-license-perms allowed">
						<div class="item-license-perms__header">
							<h3>
								You are allowed to:
							</h3>
						</div>
						<div class="item-license-perms__body">
							<div class="item-license-perms__item">
								<div class="text">
									<b>1.</b> Private use
								</div>
							</div>
							<div class="item-license-perms__item">
								<div class="text">
									<b>2.</b> Modification
								</div>
							</div>
							<div class="item-license-perms__item">
								<div class="text">
									<b>3.</b> Delete sections as you see fit
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-xl-6">
					<div class="item-license-perms denied">
						<div class="item-license-perms__header">
							<h3>
								You are not allowed to:
							</h3>
						</div>
						<div class="item-license-perms__body">
							<div class="item-license-perms__item">
								<div class="text">
									<b>1.</b> Resell
								</div>
							</div>
							<div class="item-license-perms__item">
								<div class="text">
									<b>2.</b> Distribute
								</div>
							</div>
							<div class="item-license-perms__item">
								<div class="text">
									<b>3.</b> Trade this product in any way without permission
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="next-action">
				<div class="agreement-action">
					<div class="agree">
						<input type="checkbox" id="license-agreement-checkbox" data-onchange="license_agreement">
						<label for="license-agreement-checkbox"> I agree to the terms of use and privacy policy</label>
					</div>
					<button data-anchor="?p=requirements" id="continue" class="btn btn-info" disabled="true">
						Continue
					</button>
				</div>
			</div>
		</div>
	</div>
</div>