<div class="timeline-placeholder">
	<div class="icon">
		<div class="icon__bg">
			<?php if ($cl["page_tab"] == 'notifs'): ?>
				<?php echo cl_ficon('notifications'); ?>
			<?php else: ?>
				<?php echo cl_ficon('comment_mention'); ?>
			<?php endif; ?>
		</div>
	</div>
	<div class="pl-message">
		<?php if ($cl["page_tab"] == 'notifs'): ?>
			<h4>
				<?php echo cl_translate("No notifications yet!"); ?>
			</h4>
			<p>
				<?php echo cl_translate("There seems to be you have no notifications yet. All notifications about replies to your posts, likes, etc., will be displayed here."); ?>
			</p>
		<?php else: ?>
			<h4>
				<?php echo cl_translate("No mentions yet!"); ?>
			</h4>
			<p>
				<?php echo cl_translate("There seems to be no mention of you. All links to you in user publications will be displayed here."); ?>
			</p>
		<?php endif; ?>
	</div>
</div>